name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  server_deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/reactive_bird:latest
      -
        name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.REMOTE_PASSPHRASE }}
          username: ${{ secrets.REMOTE_USER }}
          script: cd reactive-bird && git pull origin master && docker pull ${{ secrets.DOCKER_USERNAME }}/reactive_bird:latest && docker-compose up -d
